updates:
- assignees:
  - '@devgrugold'
  commit-message:
    prefix: 'chore(deps): '
  directory: /
  groups:
    dev-dependencies:
      dependency-type: development
    production-dependencies:
      dependency-type: production
  open-pull-requests-limit: 10
  package-ecosystem: npm
  reviewers:
  - '@devgrugold'
  schedule:
    day: monday
    interval: weekly
    time: 09:00
- directory: /.github/workflows
  package-ecosystem: github-actions
  schedule:
    interval: weekly
version: 2
